author: "Tobe O <thosakwe@gmail.com>"
description: "Dart interpreter written in Dart. Highly experimental."
homepage: "https://github.com/thosakwe/dart_eval"
name: "eval"
version: "1.0.0-dev"
dependencies: 
  analyzer: "^0.29.1"
  resource: "^2.0.2"
dev_dependencies: 
  test: "^0.12.15"
environment: 
  sdk: ">=1.19.0"
